### ISSUE TITLE
Changing window-sizes leads to errors

### ISSUE THREAD

**Issue by CBrakenridge** [ADALabUCSD/DeepPostures#9]
Hi there,

Great program!

Changing the window-size to anything but default results in errors in the prediction phase, and not uniformly across all IDs, some managed to be processed (e.g. ID 021 below). Otherwise the program works robustly and well at the default window-size.

python pre_process_data.py --gt3x-dir inpact --pre-processed-dir preprocessed --gt3x-frequency 75 --window-size 5

We are using a hip-worn accelerometer that records at 75hz.

The following error occured with --window-size 5:

INFO:__main__:Starting prediction generation for the subject 021_3_2009-07-28
INFO:__main__:Completed prediction generation for the subject 021_3_2009-07-28
INFO:__main__:Starting prediction generation for the subject 040_1_2009-07-18
Traceback (most recent call last):
  File "make_predictions.py", line 290, in <module>
    cnn_window_size=args.cnn_window_size, gt3x_frequency=args.gt3x_frequency, model_ckpt_path=args.model_checkpoint_path, padding=args.padding)
  File "make_predictions.py", line 91, in generate_predictions
    int(gt3x_frequency*downsample_window), 1) for d in data], [d[1] for d in data], [d[2] for d in data]
  File "make_predictions.py", line 91, in <listcomp>
    int(gt3x_frequency*downsample_window), 1) for d in data], [d[1] for d in data], [d[2] for d in data]
ValueError: cannot reshape array of size 174150 into shape (100,3,1)

Similar issues occur at window-size 1 and 60.

Thanks for any and all support!

Cheers,

Christian

**Comment by makemebitter** [comment]
Hi Christian,

Thanks for your interest in our project, and glad to hear that it works for your dataset! Unfortunately, our pre-trained models have the `--window-size` configuration baked-in during training and cannot be changed if you use them for inference. If you want to change this parameter, please take a look at [our guide](https://adalabucsd.github.io/DeepPostures/advanced/training/) on how to train a model from scratch. Thanks for this comment; we have updated the docs accordingly to clarify this.

Best,
Yuhao
